Update maven.yml
comprobar error al generar javadocs

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -3,10 +3,10 @@ name: Compilar y Generar Javadoc
 on:
   push:
     branches:
-      - develop
+      - main
   pull_request:
     branches:
-      - develop
+      - main
 
 jobs:
   build:
@@ -27,13 +27,10 @@ jobs:
         run: mvn clean compile
 
       - name: Generar Javadoc
-        run: mvn javadoc:javadoc
+        run: mvn javadoc:javadoc || echo "Error al generar Javadoc"
 
-      - name: Forzar la creación de la carpeta Javadoc
-        run: mkdir -p target/site/apidocs/
-
-      - name: Listar archivos generados
-        run: ls -R target/site/apidocs/ || echo "La carpeta está vacía"
+      - name: Mostrar contenido de target/site/
+        run: ls -R target/site/ || echo "No se encontraron archivos en target/site/"
 
       - name: Subir Javadoc como artefacto
         uses: actions/upload-artifact@v4
